# This is the directory where the program will save
# monitors configuration files, running status and
# cached information. Write permissions must be granted.
# Some subdirectories will be created:
# - locks
# - monitors
# - status
# Example:
#       var_dir: /path/to/ripe-atlas-monitor/var/dir
var_dir:

# Verbosity level:
# - 0: only warnings and errors are produced; 
# - 1: messages from logging actions are produced;
# - 2: results from matching rules are produced too;
# - 3: information messages are logged (internal decisions about rules and results processing);
# - 4: debug messages are logged too, useful to debug monitors' configurations.
#verbosity: 0

ip_cache:
        # IP cache options:
        # - directory where cache files will be stored;
        # - expiry time
        # - whether use IXPs information or not (currently based
        #   on the PeeringDB beta API)

        # If left blank, the var_dir will be used.
        #dir: /path/to/ripe-atlas-monitor/ip_cache/dir
        
        # 604800 seconds = 1 week
        #lifetime: 604800

        #use_ixps_info: True

logging:
        # File where messages will be logged.
        # File will grow up to <max_bytes> then will be
        # rotated for <backup_cnt> times.
      
        #file_path: "/path/to/ripe-atlas-monitor/log.log"
        #max_bytes: 10000000
        #backup_cnt: 3

        email:
                # Error logging via email.
                # Only program's errors will be sent via email.
                # If the 'to_addr' option is filled, all the
                # mandatory parameters must also be configured, here
                # or in the 'default_smtp' section.

                #to_addr: ""

                # Mandatory parameters:
                #smtp_host: ""
                #smtp_port: 25
                #from_addr: ""
                #subject: ""

                # Optional parameters:
                #use_ssl: False
                #username: ""
                #password: ""
                #timeout: 60

default_smtp:
        # Default email setting used by 'email' Actions and error
        # logging system.
       
        #smtp_host: ""
        #smtp_port: 25
        #from_addr: ""
        #to_addr: ""
        #subject: ""
        #use_ssl: False
        #username: ""
        #password: ""
        #timeout: 60

default_syslog:
        # Default syslog parameters used by 'syslog' Actions.
    
        # One of "tcp", "udp", "file"
        #socket: ""

        # Only meagniful if socket = "tcp" or "udp"
        # Example:
        #       host: "127.0.0.1"
        #       port: 514
        #host: ""
        #port: 514
        
        # Only meagniful if socket = "file".
        # Example:
        #       file: "/dev/log"
        #file: ""

        # Syslog facility: one of "auth", "authpriv", "cron", "daemon", 
        # "ftp", "kern", "lpr", "mail", "news", "syslog", "user", 
        # "uucp", "local[0-7]".
        # Example:
        #       facility: "local7"
        #facility: ""

        # Syslog priority: one of "alert", "crit", "critical", "debug",
        # "emerg", "panic", "err", "error", "info", "notice", "warn",
        # "warning".
        # Example:
        #       priority: "error"
        #priority: ""

misc:
        # Email address validation pattern
        #email_addr_re: "<see Config.py>"
       
        # Prefix used to build environment variables for "run" Actions:
        #env_prefix: "RIPE_ATLAS_MONITOR_"

        # Limit for measurement results download when no starting date
        # is given.
        #msm_results_days_limit: 7

        # Text editor
        #editor: /usr/bin/vim
